name: Gotify Server
version: "1.0.0"
slug: gotify_server
description: Self-hosted notification server (Gotify) as a Home Assistant addon
startup: services
boot: auto
url: https://github.com/gotify/server
webui: "http://[HOST]:[PORT:80]/"
ingress: false
ingress_port: 80
ingress_stream: false
panel_icon: mdi:bell-ring
arch:
  - aarch64
  - amd64
  - armv7
host_network: true
ports:
  80/tcp: 8080
  443/tcp: 443
ports_description:
  80/tcp: Gotify web interface
  443/tcp: Optional HTTPS
map:
  - config:rw
  - ssl
  - share
options: {}
schema: {}