version: "2.6.3"
slug: "gotify"
description: "A simple server for sending and receiving messages in real-time per WebSocket"
url: "https://github.com/gotify/server"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
init: false
ports:
  "8080/tcp": 8080
ports_description:
  "8080/tcp": "Web interface and API"
webui: "http://[HOST]:[PORT:8080]"
ingress: true
ingress_port: 8080
ingress_entry: "/"
panel_icon: mdi:message-alert
hassio_api: true
hassio_role: default
homeassistant_api: false
options:
  log_level: info
  admin_user: admin
  admin_pass: admin
  database_path: /data/gotify.db
  upload_dir: /data/uploads
  registration: false
  plugins_dir: /data/plugins
schema:
  log_level: list(trace|debug|info|warn|error|fatal|panic)
  admin_user: str
  admin_pass: str
  database_path: str
  upload_dir: str
  registration: bool
  plugins_dir: str?